### ISSUE TITLE
Is this repo maintained? 

### ISSUE THREAD

**Issue by jsilve24** [hidaqa/dired-copy-paste#1]
Seems to have been 11 years. I would be happy to submit pull request for new features if this is maintained. Otherwise I will just maintain my fork. 

Best, 
Justin

**Comment by hidaqa** [comment]
Hi @jsilve24 ,

Thank you for your inquiry!
I'm really glad to know that you are making use of my code.
As you mentioned above, this repo is no longer maintained so would you take it over and
commit your changes to your forked repository? 

Thanks,

**Comment by jsilve24** [comment]
I would be happy to take it over.

How would you like to do that? Simplest way it seems would be for you to just add a Readme saying this is unmaintained and maintenance is continuing at jsilve24/dired-copy-paste (<https://github.com/jsilve24/dired-copy-paste>).

Thoughts?

Justin

**Comment by jsilve24** [comment]
If you would like, I would be happy to submit a simple pull request with the new readme. Just let me know.

**Comment by hidaqa** [comment]
Your proposal is great!
OK, please go ahead. I'll check your PR and merge it to this repo.

**Comment by hidaqa** [comment]
Hi @jsilve24 ,
I am grateful that you have taken over and I've merged your PR #2 into master branch.

Mark this issue as Closed.

Thanks!
